env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - google
  - plugin:security/recommended
parserOptions:
  ecmaVersion: latest
rules: {
    'arrow-parens': [2, 'always'],
    'arrow-spacing': [2, { before: true, after: true }],
    'constructor-super': 2,
    'no-const-assign': 2,
    'no-this-before-super': 2,
    'no-var': 2,
    'prefer-arrow-callback': 2,
    'prefer-const': 2,
    'prefer-template': 2
}
