version: '3.5'
services:
  smtp-server:
    container_name: smtp-server
    image: smtp-server:latest
    ports:
      - '8025:8025'
    env_file:
      - ./deployments/production/server.env
    environment:
      - SMTP_USERNAME=${secrets.SMTP_USERNAME}
      - SMTP_PASSWORD=${secrets.SMTP_PASSWORD}
    