name: nodejs linting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
        node-version: '18.x'

      - uses: stefanoeb/eslint-action@1.0.2
        with:
        files: .

      - run: npm install
      - run: eslint . --ext .js
